# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a03e05537c2c52244c5ade160b9b6aff800c4ec4172a373d01b0f45a5b1c0fb138c3f06f5abed2e1e9b3e468dae3d8139702a0b51ab561696e6add589a89cb

test:
  secret_key_base: 956c44ba9e6060f52b4865543d2af2141774f489408860d09f37783c302812acaf3acc50b064eac07245b903f3aa9363c98d9ced011bbe139c08a35b66610b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
